### PR TITLE
chore: Bump k8s deps

### PR DESCRIPTION
**Pull request by JorTurFer**
This PR bumps k8s deps to v0.30.1 and all the required changes for them:
- k8s.io/api@v0.30.1 requires go@1.22.0
- go 1.22 requires linter upgrade

### CODE REVIEW

**Review by maxsmythe — APPROVED** [review]
LGTM

**Comment by JorTurFer** [comment]
Currently there is probably a bug with v0.30.0 on openapi

**Comment by JorTurFer** [comment]
It seems that v0.30.0 is broken indeed https://github.com/kubernetes/kubernetes/issues/124540

**Comment by tenzen-y** [comment]
@JorTurFer Hi, thank you for this great progressing!
Since it seems that v1.30.1 has been released, could we move this forward?

**Comment by JorTurFer** [comment]
@maxsmythe  PTAL, I've bumped k8s deps to 0.30.1

**Review by maxsmythe — APPROVED** [review]
Thanks! Still LGTM!

@sozercan @ritazh LGTY?

**Review by sozercan — APPROVED** [review]
Sorry about the delay. LGTM, thanks!

**Pull request merged**
