### PR TITLE
add parameters to customize certificate rotator

### PR DESCRIPTION
**Pull request by lpcalisi**
Add parameters to customize Certificate Rotator.

if you want rotate more than one certificate with the same CA, this feature allows to set `certName` and `keyName` files in order to add more CertRotator instances

Additionally, segregate `CaCertValidityDuration` and `ServerCertValidityDuration`

### CODE REVIEW

**Comment by lpcalisi** [comment]
@ritazh could you review this PR? thanks!

**Review by maxsmythe — APPROVED** [review]
LGTM

**Comment by lpcalisi** [comment]
@maxsmythe 🏓

**Comment by sozercan** [comment]
@lpcalisi looks like unit test is failing, can you ptal?

`E0818 00:56:44.754175    9188 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)`
https://github.com/open-policy-agent/cert-controller/actions/runs/5732331651/job/15997197871?pr=106#step:7:127

**Comment by lpcalisi** [comment]
> @lpcalisi looks like unit test is failing, can you ptal?
> 
> `E0818 00:56:44.754175 9188 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)` https://github.com/open-policy-agent/cert-controller/actions/runs/5732331651/job/15997197871?pr=106#step:7:127

i could not reproduce the error locally, `make test` works fine. Do you have any tip?

````
18d66140cd7d:/work# make test
go test ./... -coverprofile cover.out
go: downloading github.com/pkg/errors v0.9.1
go: downloading go.uber.org/atomic v1.11.0
go: downloading k8s.io/api v0.27.2
go: downloading k8s.io/apimachinery v0.27.2
go: downloading sigs.k8s.io/controller-runtime v0.15.0
go: downloading github.com/onsi/gomega v1.27.7
go: downloading github.com/open-policy-agent/frameworks/constraint v0.0.0-20230411224310-3f237e2710fa
go: downloading k8s.io/apiextensions-apiserver v0.27.2
go: downloading k8s.io/client-go v0.27.2
go: downloading k8s.io/kube-aggregator v0.27.2
go: downloading k8s.io/klog/v2 v2.90.1
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.2.3
go: downloading k8s.io/utils v0.0.0-20230209194617-a36077c30491
go: downloading github.com/evanphx/json-patch/v5 v5.6.0
go: downloading github.com/go-logr/logr v1.2.4
go: downloading github.com/prometheus/client_golang v1.15.1
go: downloading github.com/google/go-cmp v0.5.9
go: downloading github.com/google/gofuzz v1.2.0
go: downloading golang.org/x/net v0.10.0
go: downloading sigs.k8s.io/yaml v1.3.0
go: downloading sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd
go: downloading github.com/json-iterator/go v1.1.12
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading golang.org/x/time v0.3.0
go: downloading k8s.io/kube-openapi v0.0.0-20230501164219-8b0f38b5fd1f
go: downloading github.com/prometheus/client_model v0.4.0
go: downloading github.com/prometheus/common v0.42.0
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading k8s.io/component-base v0.27.2
go: downloading gomodules.xyz/jsonpatch/v2 v2.3.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading golang.org/x/term v0.8.0
go: downloading golang.org/x/oauth2 v0.5.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/golang/protobuf v1.5.3
go: downloading github.com/google/gnostic v0.5.7-v3refs
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.2.0
go: downloading github.com/prometheus/procfs v0.9.0
go: downloading google.golang.org/protobuf v1.30.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading golang.org/x/text v0.9.0
go: downloading golang.org/x/sys v0.8.0
go: downloading github.com/imdario/mergo v0.3.12
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
go: downloading github.com/emicklei/go-restful/v3 v3.9.0
go: downloading github.com/go-openapi/swag v0.22.3
go: downloading github.com/go-openapi/jsonreference v0.20.1
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/go-openapi/jsonpointer v0.19.6
go: downloading github.com/josharian/intern v1.0.0
ok  	github.com/open-policy-agent/cert-controller/pkg/rotator	21.370s	coverage: 70.3% of statements
````

**Comment by sozercan** [comment]
@lpcalisi sorry for the delay. merged with master, looks like it is passing now

**Review by sozercan — APPROVED** [review]
thank you! lgtm

**Pull request merged**
