### PR TITLE
update to admissionregistration.k8s.io/v1

### PR DESCRIPTION
**Pull request by sozercan**
Signed-off-by: Sertac Ozercan <sozercan@gmail.com>

### CODE REVIEW

**Review by maxsmythe — APPROVED** [review]
LGTM

I think this means cert-controller requires k8s 1.16+ once this is committed?

**Comment by ritazh** [comment]
We should technically include `v1` here: https://github.com/open-policy-agent/cert-controller/blob/master/pkg/rotator/rotator_test.go#L216

**Comment by sozercan** [comment]
@maxsmythe I think so, since only v1.16+ can create `v1` webhooks

**Comment by maxsmythe** [comment]
@sozercan cool, not a blocker, just something to put in release notes for a new tag

**Review by ritazh — APPROVED** [review]

**Pull request merged**
