### PR TITLE
Initial import from Gatekeeper + renaming

### PR DESCRIPTION
**Pull request by adrianludwin**
These two commit pass go test ./... successfully. I haven't tried importing it into HNC yet, but there are virtually no diffs between the HNC version and these files, so there should be minimal changes required.

The first commit is simply a straight copy from github.com/open-policy-agent/gatekeeper, commit
c8ed7d6656232648c5d8be3207be6f641c28ffa6, plus a new go.mod. The second commit matches the Go package names to the directory names.

This is a second attempt at PR #1, which was merged before all the recommended changes had been carried out.

### CODE REVIEW

**Comment by adrianludwin** [comment]
cc @maxsmythe @ekitson

**Comment by maxsmythe** [comment]
Thank you for recreating this! Sorry for the confusion. Per ekitson's comment in the original PR, can you add a link in the description pointing to the GK commit this was forked from?

**Comment by adrianludwin** [comment]
> Thank you for recreating this! Sorry for the confusion. Per ekitson's comment in the original PR, can you add a link in the description pointing to the GK commit this was forked from?

It's in the commit message (not the PR message): https://github.com/open-policy-agent/cert-controller/pull/4/commits/d81a442b01ee13326f453a38f5d6b89efc8fd33a

I can add it to the PR message if you like, but this PR includes two commits.

**Comment by maxsmythe** [comment]
Actually, it looks like you have, it's just buried a bit. It should show up on merge: 

https://github.com/open-policy-agent/cert-controller/pull/4/commits/d81a442b01ee13326f453a38f5d6b89efc8fd33a

```
This is simply a straight copy from
github.com/open-policy-agent/gatekeeper, commit
c8ed7d6656232648c5d8be3207be6f641c28ffa6, plus a new go.mod. As it
happens, it compiles and passes all tests without any modifications.
```

**Comment by adrianludwin** [comment]
> Actually, it looks like you have, it's just buried a bit. It should show up on merge <snip>

Yup, I added it to the PR message too.

**Comment by ekitson** [comment]
Initial commit looks good! Thanks Adrian.

**Pull request merged**
