### PR TITLE
chore: Bump deps to support k8s 1.27

### PR DESCRIPTION
**Pull request by JorTurFer**
in KEDA we use this dep and we have faced with problems due to dep versions. We want to use k8s 0.27 deps, but for using them we need to use [sigs.k8s.io/controller-runtime in v0.15](https://github.com/kubernetes-sigs/controller-runtime/issues/2295#event-9171425669). 

As this is part of our dependencies, I have bumped dependencies as part of this PR and if you could cut a release with these changes would be nice. 
The team from sigs.k8s.io/controller-runtime is waiting till k8s 0.27.2 but they have released an alpha version for enabling the usage before that happens (and that's the version I have used).

### CODE REVIEW

**Review by sozercan — COMMENTED** [review]
LGTM

**Review by sozercan — APPROVED** [review]
LGTM

**Review by ritazh — APPROVED** [review]
LGTM

**Review by maxsmythe — APPROVED** [review]
LGTM

**Comment by JorTurFer** [comment]
Nice!!!
One question, will you cut a release soon? I ask for waiting it or using main branch in KEDA (no rush, I can use main branch)

**Pull request merged**
